[project]
name = "bpod-webui"
version = "0.1.0"
description = "A Python web UI to monitor the status of Bpod rigs on the local network"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bpod-core>=0.1.0a5",
    "flask>=3.1.2",
]
